# Generated by Django 3.2.5 on 2021-11-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='vote1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='vote2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='vote3',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='vote4',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
